### ISSUE TITLE
Empty samples breaks`to_SignalSum` 

### ISSUE THREAD

**Issue by brosand** [Qiskit/qiskit-dynamics#127]
Passing an empty `DiscreteSignal` into `to_SignalSum` causes an array with dimensions `(1,0)` to be transpoed to `(0,1)`, which breaks the `DiscreteSignal` `init` function. The transposition should not be applied in the empty sample case.

Current behavior (raises error):
```
from qiskit_dynamics import DiscreteSignal
from qiskit_dynamics.signals.signals import to_SignalSum

to_SignalSum(DiscreteSignal(samples=[], dt=1.))
```

To fix, add an `if` statement to `to_SignalSum` which only transposes the input samples if their size is not `(1,0)`

**Comment by antalszava** [comment]
It seems like `transpose` should get a single `tuple`, instead of multiple integers. So the calls in the source seem incorrect themselves.

See for example:
```py
Array([[0.3]]).transpose(1, 0)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-dcef55651520> in <module>
----> 1 Array([[0.3]]).transpose(1, 0)

~/qiskit-dynamics/qiskit_dynamics/array/array.py in wrapped_method(*args, **kwargs)
    176             @wraps(attr)
    177             def wrapped_method(*args, **kwargs):
--> 178                 return self._wrap(attr(*args, **kwargs))
    179 
    180             return wrapped_method

TypeError: transpose() takes from 1 to 2 positional arguments but 3 were given
```

Note that this breaks the Gradient optimization of a pulse sequence tutorial.
