### ISSUE TITLE
Accept qiskit.opflow Operators as parameters for models

### ISSUE THREAD

**Issue by donsano33** [Qiskit/qiskit-dynamics#165]
### What is the expected behavior?

Similar to how we are able to use `qiskit.quantum_info.Operator` types as parameters for models, Operators of base class `qiskit.opflow.OperatorBase` should also be usable.

### Current behaviour

Code Example:

```python
from qiskit_dynamics.solvers import Solver
from qiskit.opflow import Z
drift = Z

hamiltonian_solver = Solver(
    static_hamiltonian=drift
)
```
Throws `DispatchError: 'Dispatch does not support numpy object arrays.'`

### Solution idea

Add type `qiskit.opflow.OperatorBase` in function `qiskit_dynamics.type_utils.to_numeric_matrix_type`

**Comment by DanPuzzuoli** [comment]
Closing this based on the discussion in #167.
