### ISSUE TITLE
Investigate/update minimum numpy/scipy versions

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-dynamics#55]
A new user recently had a problem with running tutorial code (both of the first two tutorials numpy/scipy based simulations), getting the error

```
TypeError: ufunc 'nextafter' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Their numpy version was `1.19.2` (which is well above the minimum version listed for dynamics), but upgrading resolved the issue. We should find the true minimum and update the listing to avoid this problem.

**Comment by MakotoNakai** [comment]
All right. I'll work on this issue

**Comment by DanPuzzuoli** [comment]
Closing as this is open ended with no concrete plans.
