### ISSUE TITLE
Investigate Signal performance and impact on solver speed

### ISSUE THREAD

**Issue by brosand** [Qiskit/qiskit-dynamics#56]
When benchmarking sparse computations on jax vs qutip, a slowdown was observed when the `Signal` class was used in the qutip simulation. Replacing the `Signal` usage with a manually defined numpy pulse function gave a 6x speedup for a small 2-transmon simulation with 3-d qubits. In addition, vectorization also caused a slowdown, with the `np.vectorization` wrapper causing a 2x slowdown in the same process. This testing was performed with qutip, using the `qt.mesolve` function.

**Comment by DanPuzzuoli** [comment]
Obviously, ideally, the signal evaluation cost when in numpy-mode should be as close as possible to just directly writing the function in numpy.

## Speed tests

Based on the above I've done some speed tests for `Signal` evaluation in a notebook attached as [Signal_speed_tests.zip](https://github.com/Qiskit/qiskit-dynamics/files/7566715/Signal_speed_tests.zip). I've defined a simple envelope function written with numpy code, and compared speeds of the following:
1. `Signal` constructed with vectorized version of the envelope.
2. Evaluation of full signal formula using only numpy functions with no envelope vectorization.
3. Evaluation of the full signal formula using only numpy with the vectorized envelope.
4. Evaluation of the full signal formula using only numpy with `Array` wrapping and no envelope vectorization.
5. Evaluation of the full signal envelope using only numpy with `Array` wrapping and envelope vectorization.

Speed tests indicate that 2 is about 3x faster than 1, and 5 is about the same speed as 1 (indicating that the discrepancy between 1 and 2 can effectively be explained by the `Array` wrapping and vectorization). Furthermore, a variant of 2, in which the formula is evaluated as:
```
env = f(t)
exp_val = np.exp(w * t + phi)
return env.real * exp_val.real - env.imag * exp_val.imag
```
is about another 2x faster than
```
return np.real(f(t) * np.exp(w * t + phi))
```
which is the current way of evaluating the formula.

I'm somewhat amazed at the 6x speed increases in the qutip solving time based on making this swap for the coefficients - even if we achieve 6x faster `Signal` evaluation I wouldn't expect a 6x improvement in solving time given that's only part of the RHS calculation, but maybe there is more going on.

## Recommendations

To try to fix the above I think we need to:
- Eliminate the requirement that the envelope be vectorized.
    - While it's possible that when actually using the vectorized function in a vectorized way it could offer speed improvements over sequential evaluation, solvers don't do this, and solving speed takes precedence over everything else.
    - The only code that depends on this is in `Signal.draw`, so this will need to be changed.
    - The `Signal` documentation talks about the vectorized assumption and how to use `np.vectorize`, so this will need to be dropped as well.
    - Also, the behaviour when a numerical constant is passed as `envelope` currently sets up the constant function to be vectorized, so this should be modified as well.
- Change all (or as much as possible) of the `Array` wrapping in the constructors of the signal classes `to_array`.
    - If the default backend is `numpy`, this function will return a raw `numpy` array instead of wrapping it, but if hte default backend is JAX, it will actually wrap it. `to_array` shouldn't be called in any RHS evaluation as it has to check through a bunch of conditions, but for a constructor it's fine.
    - All signal classes should be checked for this.

The above changes should be simple in principle, though I think doing away with the `Array` wrapping could potentially be finicky. 

I'm going to change the name of this issue to be more specifically refer to the above as items that need to be done.

**Comment by DanPuzzuoli** [comment]
I think this situation is not as straightforward as believed in previous comments. Vectorization does slow down signal evaluation, but as a proportion of actual RHS evaluation time, some quick initial tests give that it is <1% of the time for a 2-level system. I.e. in principle it will have virtually no impact on overall solver speed (unless `Array` wrapping is further messing with solver speed). This indicates that we need to do some higher level speed tests that incorporate signal evaluation + RHS evaluation, and maybe even some full integration speed tests with solvers.

**Comment by DanPuzzuoli** [comment]
Closing as this is open ended and there is no plan to work on this.
