### ISSUE TITLE
Function to compute dressed states and frequencies

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-dynamics#74]
### What is the expected behavior?

Inputs: 
 - Static hamiltonian - a hermitian operator that is assumed to be nearly diagonal
 - Subsystem dimensions - a list of the dimensions of the tensor-factors

Outputs:
 - The 'dressed states': eigenvectors of the static hamiltonian labelled according to which computational state they correspond to.
    - E.g. this could be a dictionary whose keys are the computational state labels (strings of 0, 1, 2, ...) with values being the corresponding eigenstate
    - Alternatively, same as the above but given as two lists.
- The 'dressed frequencies': For each subsystem, the difference between the eigenvalues of the dressed first excited state and the ground state, divided by 2 pi. This could just be returned as a 1d array.

Some code for performing these steps already exists in Aer in the `HamiltonianModel._compute_drift_data()` method, so we can draw on this if it makes sense to do so.

**Comment by brosand** [comment]
Can make a `pulse_utils.py` folder
