### ISSUE TITLE
Getting started link on top menu is not working

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-dynamics#76]
### Informations

This is a documentation related issue so no qiskit version info is needed

### What is the current behavior?
Getting started link on top menu is not working, it points to a 404 page

### Steps to reproduce the problem
1. Go to https://qiskit.org/documentation/dynamics/
2. Click on _Getting started_ on top menu 
<img width="1103" alt="Captura de pantalla 2022-01-17 a las 10 35 48" src="https://user-images.githubusercontent.com/17231966/149744616-8dbf7aee-c38c-43cc-90a5-60d38ab024d7.png">

3. Wait until being redirected to the _Page not found_ page

### What is the expected behavior?
Instead of having _Page not found_ page, we should have a _Getting started_ page. If we don't have a _Getting started_ page, we should remove the option from the top menu

**Comment by brosand** [comment]
Will be fixed soon! As of right now all the getting started documentation is under development (although the links are broken). Please take a look at [This link](https://qiskit.org/documentation/dynamics/tutorials/index.html) for now.
