### ISSUE TITLE
Add diffrax solvers to solve_ode

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-dynamics#93]
[Diffrax](https://github.com/patrick-kidger/diffrax) is a JAX ODE solving library providing access to many different solvers, and more control over how computations (like back propagation) are done. It also allegedly offers speed improvements over JAX's `odeint` function for the same method and tolerances.

### What is the expected behavior?

Add access to solvers from this library through `solve_ode`.

**Comment by brosand** [comment]
#104
